### ISSUE TITLE
RankSystem Support Also

### ISSUE THREAD

**Issue by shreyop200** [GamerMJay/MCPEToDiscord#8]
**Is your feature request related to a problem? Please describe.**
Its a headache as i am using RankSystem and the plugin only support PurePerms/PureChat to get the Group Name so Whenever i use {group} it just dont send the Group Name.

**Describe the solution you'd like**
Adding the support of RankSystem Will fix this and help get rank names even with ranksystem plugin

**Describe alternatives you've considered**
None Yet.

**Additional context**
You can already read the Topic that describes everything.

**Comment by GamerMJay** [comment]
MCPEToDiscord now supports RankSystem
