### ISSUE TITLE
Plugin Dont Sends Server/Console Messages

### ISSUE THREAD

**Issue by shreyop200** [GamerMJay/MCPEToDiscord#9]
**Describe the bug**
The Plugin dont Registers the console message, like the `say Hi` then the Server sends the message, it dont register them to the server.

**To Reproduce**
1. Go to Server
2. Run 'say hi` Command
3. The Bot Dont Shows the Hi message from the server in the channel.

**Expected behavior**
It Should also Register the Server messages.

**Screenshots**
Not Applicable 

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy M30s
 - OS: Android 

**Pocketmine Version**
4.23.6

**MCPEToDiscord Version**
2.2.1-Beta

**Additional context**

**Comment by GamerMJay** [comment]
![Screenshot 2023-09-16 124035](https://github.com/GamerMJay/MCPEToDiscord/assets/66413999/116cf223-0b55-400a-b40a-b7ca272f12d1)

Hey @shreyop200 , with the PocketMine-MP 5 the whole works :), update ambesten on the newest PocketMine-MP version.

**Comment by shreyop200** [comment]
> ![Screenshot 2023-09-16 124035](https://user-images.githubusercontent.com/66413999/268443535-116cf223-0b55-400a-b40a-b7ca272f12d1.png)
> 
> Hey @shreyop200 , with the PocketMine-MP 5 the whole works :), update ambesten on the newest PocketMine-MP version.

can u please implement this update to the pm4 too? i cant just switch the whole server so.

**Comment by GamerMJay** [comment]
https://github.com/GamerMJay/MCPEToDiscord/tree/pm4

test this

**Comment by GamerMJay** [comment]
@shreyop200
